<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\CustomerServiceController;
use App\Http\Controllers\DatabaseAdminController;
use App\Http\Controllers\CompanyProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DebtController;
use App\Http\Controllers\ExecutiveReportController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\InsuranceController;
use App\Http\Controllers\InternalMessageController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\MemoController;
use App\Http\Controllers\PatientRecordController;
use App\Http\Controllers\PayrollController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('idempotency')->group(function (): void {
    Route::get('/', function (): \Illuminate\Http\JsonResponse {
        return response()->json([
            'name' => 'opticplus-api',
            'version' => 'v1',
        ]);
    });

    Route::post('/login', [AuthController::class, 'login']);
    Route::get('/company-profile', [CompanyProfileController::class, 'show']);

    Route::middleware(['auth.token', 'audit.mutations'])->group(function (): void {
        Route::get('/me', [AuthController::class, 'me']);
        Route::post('/me/profile', [AuthController::class, 'updateProfile']);
        Route::post('/me/password', [AuthController::class, 'changePassword']);
        Route::post('/company-profile', [CompanyProfileController::class, 'update']);
        Route::put('/company-profile', [CompanyProfileController::class, 'update']);
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::get('/dashboard', [DashboardController::class, 'show']);
        Route::get('/patients', [PatientRecordController::class, 'index']);
        Route::get('/patients/meta', [PatientRecordController::class, 'meta']);
        Route::get('/patients/lookup', [PatientRecordController::class, 'lookup']);
        Route::get('/patients/form-prescriptions/search', [PatientRecordController::class, 'formPrescriptionSearch']);
        Route::post('/patients', [PatientRecordController::class, 'store']);
        Route::put('/patients/{recordId}', [PatientRecordController::class, 'update']);
        Route::delete('/patients/{recordId}', [PatientRecordController::class, 'destroy']);
        Route::patch('/patients/{recordId}/status', [PatientRecordController::class, 'updateStatus']);
        Route::patch('/patients/{recordId}/assign-optometrist', [PatientRecordController::class, 'assignOptometrist']);
        Route::get('/patients/{recordId}/exam-form', [PatientRecordController::class, 'examForm']);
        Route::post('/patients/{recordId}/exam-form', [PatientRecordController::class, 'saveExamForm']);
        Route::get('/patients/{recordId}/prescriptions', [PatientRecordController::class, 'prescriptions']);
        Route::post('/patients/{recordId}/prescriptions', [PatientRecordController::class, 'storePrescription']);
        Route::get('/patients/{recordId}/payments', [PatientRecordController::class, 'payments']);
        Route::get('/patients/{recordId}/documents', [PatientRecordController::class, 'documents']);
        Route::post('/patients/{recordId}/documents', [PatientRecordController::class, 'storeDocuments']);
        Route::get('/patients/{recordId}/medical-report', [PatientRecordController::class, 'medicalReport']);
        Route::get('/glasses-prescriptions', [PatientRecordController::class, 'glassesPrescriptionIndex']);
        Route::get('/billing/meta', [BillingController::class, 'meta']);
        Route::get('/billing/patient-search', [BillingController::class, 'patientSearch']);
        Route::get('/billing', [BillingController::class, 'index']);
        Route::get('/billing/export', [BillingController::class, 'export']);
        Route::get('/billing/daily-payments', [BillingController::class, 'dailyPayments']);
        Route::put('/billing/pricing', [BillingController::class, 'updatePricing']);
        Route::post('/billing', [BillingController::class, 'store']);
        Route::get('/finance/summary', [FinanceController::class, 'summary']);
        Route::get('/finance/monitor', [FinanceController::class, 'monitor']);
        Route::get('/finance/monthly-report', [FinanceController::class, 'monthlyReport']);
        Route::get('/reports/workflow', [ExecutiveReportController::class, 'index']);
        Route::get('/reports/submissions/{reportId}', [ExecutiveReportController::class, 'show']);
        Route::post('/reports/submissions', [ExecutiveReportController::class, 'store']);
        Route::post('/reports/submissions/{reportId}/review', [ExecutiveReportController::class, 'review']);
        Route::post('/reports/submissions/{reportId}/push', [ExecutiveReportController::class, 'pushToCeo']);
        Route::get('/finance/sales', [FinanceController::class, 'sales']);
        Route::get('/finance/expenses', [FinanceController::class, 'expenses']);
        Route::post('/finance/expenses', [FinanceController::class, 'storeExpense']);
        Route::put('/finance/expenses/{expenseId}', [FinanceController::class, 'updateExpense']);
        Route::delete('/finance/expenses/{expenseId}', [FinanceController::class, 'deleteExpense']);
        Route::get('/finance/expense-categories', [FinanceController::class, 'expenseCategories']);
        Route::post('/finance/expense-categories', [FinanceController::class, 'storeExpenseCategory']);
        Route::put('/finance/expense-categories/{categoryId}', [FinanceController::class, 'updateExpenseCategory']);
        Route::delete('/finance/expense-categories/{categoryId}', [FinanceController::class, 'deleteExpenseCategory']);
        Route::get('/finance/payments', [FinanceController::class, 'payments']);
        Route::get('/finance/payments/{billingId}', [FinanceController::class, 'paymentDetail']);
        Route::post('/finance/payments/{billingId}', [FinanceController::class, 'storePayment']);
        Route::post('/finance/payments/{billingId}/paystack/initialize', [FinanceController::class, 'initializePaystackPayment']);
        Route::post('/finance/payments/{billingId}/paystack/verify', [FinanceController::class, 'verifyPaystackPayment']);
        Route::get('/debts/meta', [DebtController::class, 'meta']);
        Route::get('/debts', [DebtController::class, 'index']);
        Route::post('/debts', [DebtController::class, 'store']);
        Route::get('/debts/{debtId}', [DebtController::class, 'show']);
        Route::put('/debts/{debtId}', [DebtController::class, 'update']);
        Route::patch('/debts/{debtId}/status', [DebtController::class, 'updateStatus']);
        Route::post('/debts/{debtId}/payments', [DebtController::class, 'storePayment']);
        Route::get('/debts/{debtId}/payments', [DebtController::class, 'payments']);
        Route::post('/debts/{debtId}/restructure', [DebtController::class, 'restructure']);
        Route::get('/insurance/meta', [InsuranceController::class, 'meta']);
        Route::get('/insurance/providers', [InsuranceController::class, 'providerCatalog']);
        Route::post('/insurance/providers', [InsuranceController::class, 'storeProvider']);
        Route::delete('/insurance/providers/{providerId}', [InsuranceController::class, 'deleteProvider']);
        Route::get('/insurance/remittances', [InsuranceController::class, 'remittances']);
        Route::post('/insurance/remittances', [InsuranceController::class, 'storeRemittance']);
        Route::get('/insurance/claims', [InsuranceController::class, 'index']);
        Route::get('/insurance/claims/report', [InsuranceController::class, 'report']);
        Route::post('/insurance/claims', [InsuranceController::class, 'store']);
        Route::put('/insurance/claims/{claimId}', [InsuranceController::class, 'updateClaim']);
        Route::delete('/insurance/claims/{claimId}', [InsuranceController::class, 'deleteClaim']);
        Route::patch('/insurance/claims/{claimId}/mark-paid', [InsuranceController::class, 'markPaid']);
        Route::patch('/insurance/claims/{claimId}/mark-pending', [InsuranceController::class, 'markPending']);
        Route::get('/inventory', [InventoryController::class, 'overview']);
        Route::post('/inventory', [InventoryController::class, 'store']);
        Route::put('/inventory/{productId}', [InventoryController::class, 'update']);
        Route::delete('/inventory/{productId}', [InventoryController::class, 'destroy']);
        Route::get('/inventory/lens-tracker', [InventoryController::class, 'lensTracker']);
        Route::get('/inventory/bsmi-tracker', [InventoryController::class, 'bsmiTracker']);
        Route::post('/inventory/lens-tracker/{billingId}', [InventoryController::class, 'storeLensCost']);
        Route::delete('/inventory/lens-tracker/{billingId}', [InventoryController::class, 'deleteLensCost']);
        Route::get('/manager/overview', [ManagerController::class, 'overview']);
        Route::get('/manager/audit-logs', [AuditLogController::class, 'index']);
        Route::get('/manager/users', [ManagerController::class, 'users']);
        Route::post('/manager/users', [ManagerController::class, 'storeUser']);
        Route::post('/manager/users/{userId}', [ManagerController::class, 'updateUser']);
        Route::put('/manager/users/{userId}', [ManagerController::class, 'updateUser']);
        Route::patch('/manager/users/{userId}/toggle-status', [ManagerController::class, 'toggleUserStatus']);
        Route::patch('/manager/users/{userId}/reset-password', [ManagerController::class, 'resetUserPassword']);
        Route::delete('/manager/users/{userId}', [ManagerController::class, 'deleteUser']);
        Route::get('/manager/database-admin/meta', [DatabaseAdminController::class, 'meta']);
        Route::get('/manager/database-admin/tables', [DatabaseAdminController::class, 'tables']);
        Route::get('/manager/database-admin/table', [DatabaseAdminController::class, 'table']);
        Route::get('/manager/database-admin', [DatabaseAdminController::class, 'index']);
        Route::get('/manager/database-admin/{resource}/duplicates', [DatabaseAdminController::class, 'duplicates']);
        Route::get('/manager/database-admin/{resource}/{recordId}', [DatabaseAdminController::class, 'show']);
        Route::put('/manager/database-admin/{resource}/{recordId}', [DatabaseAdminController::class, 'update']);
        Route::delete('/manager/database-admin/{resource}/{recordId}', [DatabaseAdminController::class, 'destroy']);
        Route::get('/manager/employees', [ManagerController::class, 'employees']);
        Route::get('/manager/employees/{employeeId}', [ManagerController::class, 'employeeDetail']);
        Route::post('/manager/employees/{employeeId}', [ManagerController::class, 'updateEmployee']);
        Route::get('/memos/meta', [MemoController::class, 'meta']);
        Route::get('/memos', [MemoController::class, 'index']);
        Route::post('/memos', [MemoController::class, 'store']);
        Route::put('/memos/{memoId}', [MemoController::class, 'update']);
        Route::post('/memos/{memoId}/update', [MemoController::class, 'update']);
        Route::get('/memos/{memoId}', [MemoController::class, 'show']);
        Route::post('/memos/{memoId}/decision', [MemoController::class, 'decide']);
        Route::get('/messages/users', [InternalMessageController::class, 'users']);
        Route::get('/messages/inbox', [InternalMessageController::class, 'inbox']);
        Route::get('/messages/unread', [InternalMessageController::class, 'unread']);
        Route::get('/messages/threads/{peerId}', [InternalMessageController::class, 'thread']);
        Route::post('/messages/threads/{peerId}/read', [InternalMessageController::class, 'markThreadRead']);
        Route::post('/messages', [InternalMessageController::class, 'store']);
        Route::get('/payroll/meta', [PayrollController::class, 'meta']);
        Route::get('/payroll', [PayrollController::class, 'index']);
        Route::post('/payroll/advances', [PayrollController::class, 'storeAdvance']);
        Route::post('/payroll/process', [PayrollController::class, 'processPayroll']);
        Route::post('/payroll/process-bulk', [PayrollController::class, 'processBulk']);
        Route::delete('/payroll/history/{historyId}', [PayrollController::class, 'deleteHistory']);
        Route::get('/payroll/bank-register', [PayrollController::class, 'bankRegister']);
        Route::post('/payroll/bank-register/deposits', [PayrollController::class, 'storeBankDeposit']);
        Route::post('/payroll/bank-register/balance', [PayrollController::class, 'updateBankBalance']);
        Route::get('/customer-service', [CustomerServiceController::class, 'dashboard']);
        Route::post('/customer-service/templates', [CustomerServiceController::class, 'storeTemplate']);
        Route::put('/customer-service/templates/{templateId}', [CustomerServiceController::class, 'updateTemplate']);
        Route::delete('/customer-service/templates/{templateId}', [CustomerServiceController::class, 'deleteTemplate']);
        Route::post('/customer-service/messages/send', [CustomerServiceController::class, 'sendMessage']);
        Route::post('/customer-service/pickups/{billingId}/ready', [CustomerServiceController::class, 'markReady']);
        Route::post('/customer-service/pickups/{billingId}/not-ready', [CustomerServiceController::class, 'markNotReady']);
        Route::post('/customer-service/pickups/{billingId}/picked-up', [CustomerServiceController::class, 'markPickedUp']);
    });
});
