<?php

declare(strict_types=1);

/**
 * AUTO-GENERATED by database/schema/build_opticplus_manifest.php
 * Do not edit by hand; re-run the build script after updating the source dump.
 */

return [
    'tables' => array (
  0 => 
  array (
    'name' => 'appointments',
    'create' => 'CREATE TABLE IF NOT EXISTS `appointments` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `sex` varchar(10) NOT NULL,
  `dob` date DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(20) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `residence` varchar(255) DEFAULT NULL,
  `doctor` varchar(100) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `appointment_date` date NOT NULL,
  `appointment_time` time NOT NULL,
  `optometrist_id` int(11) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT \'pending\'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `appointments` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `appointments` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  1 => 
  array (
    'name' => 'attendance',
    'create' => 'CREATE TABLE IF NOT EXISTS `attendance` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `staff_id` varchar(20) DEFAULT NULL,
  `clock_in_time` datetime DEFAULT NULL,
  `clock_out_time` datetime DEFAULT NULL,
  `date` date NOT NULL,
  `branch` varchar(50) DEFAULT NULL,
  `location_verified` tinyint(1) DEFAULT 0,
  `coordinates` varchar(100) DEFAULT NULL,
  `distance_from_branch` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `attendance` ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);',
      1 => 'ALTER TABLE `attendance` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  2 => 
  array (
    'name' => 'bank_balance',
    'create' => 'CREATE TABLE IF NOT EXISTS `bank_balance` (
  `id` int(11) NOT NULL,
  `balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `last_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `bank_balance` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `bank_balance` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  3 => 
  array (
    'name' => 'bank_deposits',
    'create' => 'CREATE TABLE IF NOT EXISTS `bank_deposits` (
  `id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `date` date NOT NULL,
  `description` text NOT NULL,
  `type` enum(\'deposit\',\'withdrawal\',\'adjustment\') DEFAULT \'deposit\',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `bank_deposits` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `bank_deposits` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  4 => 
  array (
    'name' => 'billing',
    'create' => 'CREATE TABLE IF NOT EXISTS `billing` (
  `id` int(11) NOT NULL,
  `patient_id` int(11) DEFAULT NULL,
  `folder_id` varchar(50) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `consultation_price` decimal(10,2) NOT NULL,
  `frame_price` decimal(10,2) NOT NULL,
  `lens_price` decimal(10,2) NOT NULL,
  `case_price` decimal(10,2) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `discount` decimal(10,2) NOT NULL,
  `tax` decimal(10,2) NOT NULL,
  `nhil_amount` decimal(10,2) DEFAULT 0.00,
  `getfund_amount` decimal(10,2) DEFAULT 0.00,
  `covid_levy_amount` decimal(10,2) DEFAULT 0.00,
  `vat_amount` decimal(10,2) DEFAULT 0.00,
  `vat_flat_rate_amount` decimal(10,2) DEFAULT 0.00,
  `vat` int(11) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `health_insurance` enum(\'NONE\',\'APEX\',\'ACACIA\',\'GLICO\',\'PREMIERE HEALTH INSURANCE\',\'NATIONWIDE\',\'OTHER\') NOT NULL DEFAULT \'NONE\',
  `date` date DEFAULT NULL,
  `status` varchar(20) DEFAULT \'balance_remaining\',
  `balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `prescription_id` bigint(20) UNSIGNED DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `receipt_number` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `billing` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `receipt_number` (`receipt_number`),
  ADD KEY `patient_id` (`patient_id`),
  ADD KEY `fk_customer_id` (`customer_id`),
  ADD KEY `idx_date` (`date`),
  ADD KEY `idx_billing_id` (`id`),
  ADD KEY `idx_folder_id` (`folder_id`);',
      1 => 'ALTER TABLE `billing` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  5 => 
  array (
    'name' => 'billing_frames',
    'create' => 'CREATE TABLE IF NOT EXISTS `billing_frames` (
  `id` int(11) NOT NULL,
  `billing_id` int(11) NOT NULL,
  `frame_code_id` varchar(50) NOT NULL,
  `frame_price` decimal(10,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `billing_frames` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_billing_frame` (`billing_id`,`frame_code_id`),
  ADD KEY `billing_id` (`billing_id`);',
      1 => 'ALTER TABLE `billing_frames` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  6 => 
  array (
    'name' => 'branch_locations',
    'create' => 'CREATE TABLE IF NOT EXISTS `branch_locations` (
  `id` int(11) NOT NULL,
  `branch_name` varchar(100) NOT NULL,
  `latitude` decimal(10,8) NOT NULL,
  `longitude` decimal(11,8) NOT NULL,
  `radius_meters` int(11) NOT NULL DEFAULT 20,
  `address` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `branch_locations` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `branch_name` (`branch_name`);',
      1 => 'ALTER TABLE `branch_locations` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  7 => 
  array (
    'name' => 'bsmi_transactions',
    'create' => 'CREATE TABLE IF NOT EXISTS `bsmi_transactions` (
  `id` int(11) NOT NULL,
  `billing_id` int(11) NOT NULL,
  `frame_code` varchar(50) NOT NULL,
  `min_price` decimal(10,2) NOT NULL,
  `selling_price` decimal(10,2) NOT NULL,
  `margin` decimal(10,2) GENERATED ALWAYS AS (`selling_price` - `min_price`) STORED,
  `staff_share` decimal(10,2) GENERATED ALWAYS AS ((`selling_price` - `min_price`) * 0.40) STORED,
  `reinvestment_share` decimal(10,2) GENERATED ALWAYS AS ((`selling_price` - `min_price`) * 0.30) STORED,
  `tax_share` decimal(10,2) GENERATED ALWAYS AS ((`selling_price` - `min_price`) * 0.15) STORED,
  `operational_share` decimal(10,2) GENERATED ALWAYS AS ((`selling_price` - `min_price`) * 0.15) STORED,
  `sold_by` int(11) NOT NULL,
  `branch` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `amount_allocated` decimal(10,2) DEFAULT 0.00,
  `lens_paid` decimal(10,2) DEFAULT 0.00,
  `frame_min_paid` decimal(10,2) DEFAULT 0.00,
  `surplus_for_bsmi` decimal(10,2) DEFAULT 0.00,
  `payment_method` varchar(50) DEFAULT NULL,
  `insurance_amount` decimal(10,2) DEFAULT 0.00,
  `insurance_status` enum(\'none\',\'pending\',\'claimed\',\'paid\') DEFAULT \'none\',
  `cash_amount` decimal(10,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `bsmi_transactions` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_billing_frame` (`billing_id`,`frame_code`),
  ADD KEY `idx_frame_code` (`frame_code`),
  ADD KEY `idx_sold_by` (`sold_by`),
  ADD KEY `idx_created_at` (`created_at`),
  ADD KEY `idx_branch` (`branch`);',
      1 => 'ALTER TABLE `bsmi_transactions` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  8 => 
  array (
    'name' => 'customers',
    'create' => 'CREATE TABLE IF NOT EXISTS `customers` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `email` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `customers` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `customers` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  9 => 
  array (
    'name' => 'debts',
    'create' => 'CREATE TABLE IF NOT EXISTS `debts` (
  `id` int(11) NOT NULL,
  `debtor_name` varchar(255) NOT NULL COMMENT \'Name of person/entity we owe money to\',
  `debt_type` enum(\'loan\',\'supplier_credit\',\'overdraft\',\'lease\',\'other\') NOT NULL DEFAULT \'loan\',
  `category` varchar(100) NOT NULL COMMENT \'Bank loan, Equipment lease, Supplier credit, etc\',
  `description` text DEFAULT NULL,
  `principal_amount` decimal(15,2) NOT NULL COMMENT \'Original loan amount\',
  `interest_rate` decimal(5,2) DEFAULT NULL COMMENT \'Annual interest rate %\',
  `interest_type` enum(\'fixed\',\'variable\',\'none\') DEFAULT \'fixed\',
  `total_amount` decimal(15,2) NOT NULL COMMENT \'Principal + interest total\',
  `amount_paid` decimal(15,2) NOT NULL DEFAULT 0.00,
  `monthly_payment` decimal(15,2) DEFAULT NULL COMMENT \'Calculated monthly payment amount\',
  `lender_name` varchar(255) DEFAULT NULL COMMENT \'Bank name, supplier name, etc\',
  `lender_contact` varchar(255) DEFAULT NULL,
  `lender_phone` varchar(20) DEFAULT NULL,
  `lender_email` varchar(100) DEFAULT NULL,
  `start_date` date NOT NULL,
  `due_date` date NOT NULL,
  `term_months` int(11) DEFAULT NULL COMMENT \'Loan term in months\',
  `payment_frequency` enum(\'monthly\',\'quarterly\',\'annually\',\'one-time\') DEFAULT \'monthly\',
  `next_payment_date` date DEFAULT NULL,
  `next_payment_amount` decimal(15,2) DEFAULT NULL,
  `status` enum(\'active\',\'paid\',\'defaulted\',\'restructured\',\'pending\') NOT NULL DEFAULT \'active\',
  `collateral` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `debts` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_status` (`status`),
  ADD KEY `idx_due_date` (`due_date`),
  ADD KEY `idx_next_payment` (`next_payment_date`),
  ADD KEY `idx_debt_type` (`debt_type`),
  ADD KEY `created_by` (`created_by`);',
      1 => 'ALTER TABLE `debts` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  10 => 
  array (
    'name' => 'debt_payments',
    'create' => 'CREATE TABLE IF NOT EXISTS `debt_payments` (
  `id` int(11) NOT NULL,
  `debt_id` int(11) NOT NULL,
  `payment_date` date NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `payment_method` enum(\'cash\',\'bank_transfer\',\'cheque\',\'mobile_money\',\'other\') NOT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `receipt_path` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `recorded_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `debt_payments` ADD PRIMARY KEY (`id`),
  ADD KEY `debt_id` (`debt_id`),
  ADD KEY `idx_payment_date` (`payment_date`),
  ADD KEY `recorded_by` (`recorded_by`);',
      1 => 'ALTER TABLE `debt_payments` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  11 => 
  array (
    'name' => 'debt_reminders',
    'create' => 'CREATE TABLE IF NOT EXISTS `debt_reminders` (
  `id` int(11) NOT NULL,
  `debt_id` int(11) NOT NULL,
  `reminder_date` date NOT NULL,
  `reminder_type` enum(\'payment_due\',\'late_payment\',\'review\',\'other\') NOT NULL,
  `message` text NOT NULL,
  `sent_to` varchar(255) DEFAULT NULL,
  `sent_via` enum(\'email\',\'sms\',\'notification\') DEFAULT NULL,
  `status` enum(\'pending\',\'sent\',\'cancelled\') DEFAULT \'pending\',
  `sent_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `debt_reminders` ADD PRIMARY KEY (`id`),
  ADD KEY `debt_id` (`debt_id`),
  ADD KEY `idx_reminder_date` (`reminder_date`),
  ADD KEY `idx_status` (`status`);',
      1 => 'ALTER TABLE `debt_reminders` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  12 => 
  array (
    'name' => 'employees',
    'create' => 'CREATE TABLE IF NOT EXISTS `employees` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `salary` decimal(10,2) NOT NULL,
  `ssnit_number` varchar(255) NOT NULL,
  `profile_image` varchar(255) DEFAULT \'default_profile.png\'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `employees` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `employees` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  13 => 
  array (
    'name' => 'employees_comprehensive',
    'create' => 'CREATE TABLE IF NOT EXISTS `employees_comprehensive` (
  `id` int(11) NOT NULL,
  `staff_id` varchar(20) DEFAULT NULL,
  `ghana_card_name` varchar(255) NOT NULL,
  `ghana_card_number` varchar(50) NOT NULL,
  `date_of_birth` date NOT NULL,
  `gender` enum(\'Male\',\'Female\',\'Other\') NOT NULL,
  `marital_status` enum(\'Single\',\'Married\',\'Divorced\',\'Widowed\') NOT NULL,
  `residential_address` text NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `email` varchar(100) NOT NULL,
  `emergency_contact_name` varchar(255) NOT NULL,
  `emergency_contact_phone` varchar(20) NOT NULL,
  `job_title` varchar(100) NOT NULL,
  `department` varchar(100) NOT NULL,
  `branch` enum(\'Madina\',\'Labadi\') NOT NULL,
  `employment_type` enum(\'Full-Time\',\'Part-Time\',\'Contract\') NOT NULL,
  `employment_year` int(4) NOT NULL,
  `employment_month` int(2) NOT NULL,
  `date_employed` date NOT NULL,
  `supervisor` varchar(255) NOT NULL DEFAULT \'General Manager\',
  `ssnit_number` varchar(50) NOT NULL,
  `tin_number` varchar(50) DEFAULT NULL,
  `bank_name` varchar(100) NOT NULL,
  `bank_branch` varchar(100) NOT NULL,
  `bank_other` varchar(100) DEFAULT NULL,
  `account_name` varchar(255) NOT NULL,
  `account_number` varchar(50) NOT NULL,
  `salary` decimal(10,2) NOT NULL,
  `highest_qualification` varchar(100) NOT NULL,
  `institution` varchar(255) NOT NULL,
  `year_completed` int(4) NOT NULL,
  `professional_license` varchar(100) DEFAULT NULL,
  `photo_path` varchar(255) DEFAULT NULL,
  `selfie_path` varchar(255) DEFAULT NULL,
  `declaration_agreed` tinyint(1) NOT NULL DEFAULT 0,
  `digital_signature` varchar(255) NOT NULL,
  `submission_date` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `status` enum(\'active\',\'inactive\',\'terminated\') DEFAULT \'active\'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `employees_comprehensive` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `ghana_card_number` (`ghana_card_number`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `ssnit_number` (`ssnit_number`),
  ADD UNIQUE KEY `uk_staff_id` (`staff_id`),
  ADD KEY `idx_branch` (`branch`),
  ADD KEY `idx_job_title` (`job_title`);',
      1 => 'ALTER TABLE `employees_comprehensive` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  14 => 
  array (
    'name' => 'expenses',
    'create' => 'CREATE TABLE IF NOT EXISTS `expenses` (
  `expense_id` int(11) NOT NULL,
  `description` varchar(255) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `date` date NOT NULL,
  `category` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `expenses` ADD PRIMARY KEY (`expense_id`),
  ADD KEY `idx_category_date` (`category`,`date`);',
      1 => 'ALTER TABLE `expenses` MODIFY `expense_id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  15 => 
  array (
    'name' => 'glasses_prescriptions',
    'create' => 'CREATE TABLE IF NOT EXISTS `glasses_prescriptions` (
  `patient_id` int(11) NOT NULL,
  `folder_id` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `sph_od` varchar(20) DEFAULT NULL,
  `sph_os` varchar(20) DEFAULT NULL,
  `cyl_od` varchar(20) DEFAULT NULL,
  `cyl_os` varchar(20) DEFAULT NULL,
  `axis_od` varchar(10) DEFAULT NULL,
  `axis_os` varchar(10) DEFAULT NULL,
  `add_od` varchar(20) DEFAULT NULL,
  `add_os` varchar(20) DEFAULT NULL,
  `ipd` varchar(255) DEFAULT NULL,
  `lens_type` varchar(255) DEFAULT NULL,
  `lens_material` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `status` varchar(20) DEFAULT \'pending\',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `lens_price` decimal(10,2) DEFAULT 0.00,
  `prescription_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `glasses_prescriptions` ADD PRIMARY KEY (`patient_id`);',
      1 => 'ALTER TABLE `glasses_prescriptions` MODIFY `patient_id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  16 => 
  array (
    'name' => 'insurance_claims',
    'create' => 'CREATE TABLE IF NOT EXISTS `insurance_claims` (
  `id` int(11) NOT NULL,
  `patient_id` int(11) NOT NULL,
  `folder_id` varchar(255) NOT NULL,
  `insurance_provider` enum(\'APEX\',\'ACACIA\',\'GLICO\',\'PREMIERE HEALTH INSURANCE\',\'NATIONWIDE\') NOT NULL,
  `insurance_number` varchar(255) NOT NULL,
  `insurance_package` varchar(255) NOT NULL,
  `patient_organization` varchar(255) NOT NULL,
  `amount_paid` decimal(10,2) NOT NULL,
  `date` date NOT NULL,
  `status` enum(\'claimed\',\'paid\',\'pending\') DEFAULT \'pending\',
  `billing_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `insurance_claims` ADD PRIMARY KEY (`id`),
  ADD KEY `fk_insurance_claims_billing` (`billing_id`);',
      1 => 'ALTER TABLE `insurance_claims` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  17 => 
  array (
    'name' => 'inventory_movements',
    'create' => 'CREATE TABLE IF NOT EXISTS `inventory_movements` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `product_id` int(11) NOT NULL,
  `branch_id` int(11) DEFAULT 2,
  `movement_type` enum(\'opening\',\'restock\',\'sale\',\'adjustment\',\'return\',\'damage\',\'transfer_out\',\'transfer_in\') NOT NULL,
  `quantity_change` int(11) NOT NULL,
  `stock_before` int(11) DEFAULT NULL,
  `stock_after` int(11) DEFAULT NULL,
  `reference_table` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `movement_at` datetime NOT NULL DEFAULT current_timestamp(),
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `inventory_movements` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_product_branch_time` (`product_id`,`branch_id`,`movement_at`),
  ADD KEY `idx_branch_time` (`branch_id`,`movement_at`),
  ADD KEY `idx_product_id` (`product_id`),
  ADD KEY `idx_reference` (`reference_table`,`reference_id`),
  ADD KEY `fk_inv_movement_user` (`created_by`);',
      1 => 'ALTER TABLE `inventory_movements` MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;',
    ),
  ),
  18 => 
  array (
    'name' => 'invoices',
    'create' => 'CREATE TABLE IF NOT EXISTS `invoices` (
  `id` int(11) NOT NULL,
  `invoice_number` varchar(50) NOT NULL,
  `date` date NOT NULL,
  `customer_name` varchar(255) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `vat` decimal(5,2) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `invoices` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `invoices` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  19 => 
  array (
    'name' => 'invoice_items',
    'create' => 'CREATE TABLE IF NOT EXISTS `invoice_items` (
  `id` int(11) NOT NULL,
  `invoice_number` varchar(50) NOT NULL,
  `item` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `invoice_items` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `invoice_items` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  20 => 
  array (
    'name' => 'items',
    'create' => 'CREATE TABLE IF NOT EXISTS `items` (
  `id` int(11) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `category` varchar(50) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `code_id` varchar(50) NOT NULL,
  `in_stock` tinyint(1) NOT NULL DEFAULT 1,
  `stock_quantity` int(11) NOT NULL,
  `supplier_name` varchar(255) NOT NULL,
  `supplier_code` varchar(255) NOT NULL,
  `item_number` int(11) NOT NULL,
  `year` varchar(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `items` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `items` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  21 => 
  array (
    'name' => 'lens_costs',
    'create' => 'CREATE TABLE IF NOT EXISTS `lens_costs` (
  `id` int(11) NOT NULL,
  `billing_id` int(11) NOT NULL,
  `folder_id` varchar(50) NOT NULL,
  `patient_id` int(11) DEFAULT NULL,
  `selling_price` decimal(10,2) NOT NULL,
  `cost_price` decimal(10,2) NOT NULL,
  `profit` decimal(10,2) GENERATED ALWAYS AS (`selling_price` - `cost_price`) STORED,
  `margin_percentage` decimal(5,2) GENERATED ALWAYS AS (if(`selling_price` > 0,(`selling_price` - `cost_price`) / `selling_price` * 100,0)) STORED,
  `entered_by` int(11) DEFAULT NULL,
  `entered_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `lens_costs` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_billing_lens` (`billing_id`),
  ADD KEY `idx_date` (`entered_at`),
  ADD KEY `idx_folder_id` (`folder_id`),
  ADD KEY `entered_by` (`entered_by`);',
      1 => 'ALTER TABLE `lens_costs` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  22 => 
  array (
    'name' => 'manufacturers',
    'create' => 'CREATE TABLE IF NOT EXISTS `manufacturers` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `manufacturers` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `manufacturers` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  23 => 
  array (
    'name' => 'memos',
    'create' => 'CREATE TABLE IF NOT EXISTS `memos` (
  `id` int(11) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `memo_to` text NOT NULL,
  `memo_from` varchar(255) NOT NULL,
  `memo_date` date NOT NULL,
  `reference` varchar(100) DEFAULT NULL,
  `body` text NOT NULL,
  `cc` text DEFAULT NULL,
  `status` enum(\'draft\',\'pending_approval\',\'approved\',\'rejected\',\'sent\',\'archived\') NOT NULL DEFAULT \'draft\',
  `created_by` varchar(100) NOT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `approval_status` enum(\'pending\',\'approved\',\'rejected\') DEFAULT \'pending\',
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_by_id` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approval_notes` text DEFAULT NULL,
  `digital_signature` varchar(255) DEFAULT NULL,
  `gm_signature` varchar(255) DEFAULT NULL,
  `requires_approval` tinyint(1) DEFAULT 1,
  `priority` enum(\'low\',\'medium\',\'high\',\'urgent\') DEFAULT \'medium\',
  `has_attachments` tinyint(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `memos` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_status` (`status`),
  ADD KEY `idx_date` (`memo_date`),
  ADD KEY `idx_created_by_id` (`created_by_id`),
  ADD KEY `idx_approval_status` (`approval_status`),
  ADD KEY `idx_requires_approval` (`requires_approval`);',
      1 => 'ALTER TABLE `memos` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  24 => 
  array (
    'name' => 'memo_approvals',
    'create' => 'CREATE TABLE IF NOT EXISTS `memo_approvals` (
  `id` int(11) NOT NULL,
  `memo_id` int(11) NOT NULL,
  `approver_id` int(11) NOT NULL,
  `approver_name` varchar(100) NOT NULL,
  `approver_role` varchar(50) NOT NULL,
  `action` enum(\'submitted\',\'approved\',\'rejected\',\'reviewed\',\'forwarded\') NOT NULL,
  `notes` text DEFAULT NULL,
  `signature_path` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `memo_approvals` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_memo_id` (`memo_id`),
  ADD KEY `idx_approver_id` (`approver_id`);',
      1 => 'ALTER TABLE `memo_approvals` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  25 => 
  array (
    'name' => 'memo_attachments',
    'create' => 'CREATE TABLE IF NOT EXISTS `memo_attachments` (
  `id` int(11) NOT NULL,
  `memo_id` int(11) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `file_path` varchar(255) NOT NULL,
  `file_type` varchar(50) NOT NULL,
  `file_size` int(11) NOT NULL,
  `uploaded_by` int(11) NOT NULL,
  `uploaded_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `memo_attachments` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_memo_id` (`memo_id`),
  ADD KEY `idx_uploaded_by` (`uploaded_by`);',
      1 => 'ALTER TABLE `memo_attachments` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  26 => 
  array (
    'name' => 'notes',
    'create' => 'CREATE TABLE IF NOT EXISTS `notes` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `note` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `notes` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `notes` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  27 => 
  array (
    'name' => 'patient_documents',
    'create' => 'CREATE TABLE IF NOT EXISTS `patient_documents` (
  `id` int(11) NOT NULL,
  `folder_id` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_path` varchar(255) NOT NULL,
  `uploaded_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `patient_documents` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `patient_documents` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  28 => 
  array (
    'name' => 'patient_form_data',
    'create' => 'CREATE TABLE IF NOT EXISTS `patient_form_data` (
  `id` int(11) NOT NULL,
  `folder_id` varchar(50) NOT NULL,
  `user_id` int(11) NOT NULL,
  `version` int(11) NOT NULL,
  `form_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`form_data`)),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `status` enum(\'draft\',\'completed\') NOT NULL DEFAULT \'draft\'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `patient_form_data` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `folder_id` (`folder_id`,`version`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `idx_status` (`status`);',
      1 => 'ALTER TABLE `patient_form_data` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  29 => 
  array (
    'name' => 'patient_records',
    'create' => 'CREATE TABLE IF NOT EXISTS `patient_records` (
  `id` int(11) NOT NULL,
  `date` date NOT NULL,
  `folder_id` varchar(50) NOT NULL,
  `surname` varchar(100) NOT NULL,
  `firstname` varchar(100) NOT NULL,
  `othernames` varchar(100) DEFAULT NULL,
  `sex` varchar(10) NOT NULL,
  `dob` date DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(20) NOT NULL,
  `assigned_optometrist_id` int(11) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `residence` varchar(255) DEFAULT NULL,
  `purpose` varchar(50) NOT NULL,
  `comment` text DEFAULT NULL,
  `status` enum(\'pending\',\'seen\') DEFAULT \'pending\',
  `name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `patient_records` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `uk_folder_id` (`folder_id`),
  ADD KEY `folder_id` (`folder_id`),
  ADD KEY `idx_status` (`status`),
  ADD KEY `idx_created_at` (`created_at`);',
      1 => 'ALTER TABLE `patient_records` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  30 => 
  array (
    'name' => 'paye',
    'create' => 'CREATE TABLE IF NOT EXISTS `paye` (
  `id` int(11) NOT NULL,
  `employee_name` varchar(255) NOT NULL,
  `salary` decimal(10,2) NOT NULL,
  `paye_amount` decimal(10,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `paye` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `paye` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  31 => 
  array (
    'name' => 'payments',
    'create' => 'CREATE TABLE IF NOT EXISTS `payments` (
  `id` int(11) NOT NULL,
  `patient_id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `payment_date` date NOT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `payments` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `payments` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  32 => 
  array (
    'name' => 'payroll_history',
    'create' => 'CREATE TABLE IF NOT EXISTS `payroll_history` (
  `id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `employee_name` varchar(255) NOT NULL,
  `gross_salary` decimal(10,2) NOT NULL,
  `advance_deduction` decimal(10,2) DEFAULT 0.00,
  `net_salary` decimal(10,2) NOT NULL,
  `pay_month` int(11) NOT NULL,
  `pay_year` int(11) NOT NULL,
  `payment_date` datetime NOT NULL,
  `notes` text DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT \'bank_transfer\',
  `created_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `payroll_history` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_employee` (`employee_id`),
  ADD KEY `idx_date` (`pay_year`,`pay_month`);',
      1 => 'ALTER TABLE `payroll_history` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  33 => 
  array (
    'name' => 'pos_sales',
    'create' => 'CREATE TABLE IF NOT EXISTS `pos_sales` (
  `id` int(11) NOT NULL,
  `items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`items`)),
  `amount_paid` decimal(10,2) NOT NULL,
  `discount` decimal(10,2) DEFAULT 0.00,
  `tax` decimal(10,2) DEFAULT 0.00,
  `payment_method` enum(\'Cash\',\'Paystack\') NOT NULL,
  `date` datetime NOT NULL,
  `customer_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
    ),
  ),
  34 => 
  array (
    'name' => 'prescriptions',
    'create' => 'CREATE TABLE IF NOT EXISTS `prescriptions` (
  `id` int(11) NOT NULL,
  `patient_name` varchar(255) NOT NULL,
  `details` text NOT NULL,
  `status` enum(\'pending\',\'completed\') DEFAULT \'pending\',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `prescriptions` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `prescriptions` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  35 => 
  array (
    'name' => 'procurements',
    'create' => 'CREATE TABLE IF NOT EXISTS `procurements` (
  `id` int(11) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `supplier` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `status` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `procurements` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `procurements` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  36 => 
  array (
    'name' => 'products',
    'create' => 'CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `category` enum(\'Frame\',\'Lens\',\'Case\',\'Accessory\') NOT NULL,
  `grade` char(1) DEFAULT NULL,
  `code` varchar(50) NOT NULL,
  `stock` int(11) NOT NULL,
  `manufacturer_id` int(11) DEFAULT NULL,
  `min_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `max_price` decimal(10,2) NOT NULL DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `products` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `code` (`code`),
  ADD KEY `idx_category` (`category`),
  ADD KEY `idx_code` (`code`),
  ADD KEY `fk_manufacturer` (`manufacturer_id`);',
      1 => 'ALTER TABLE `products` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  37 => 
  array (
    'name' => 'revenue',
    'create' => 'CREATE TABLE IF NOT EXISTS `revenue` (
  `sale_id` int(10) NOT NULL,
  `folder_id` int(11) NOT NULL,
  `billing_id` int(11) NOT NULL,
  `patient_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `amount_paid` decimal(10,2) NOT NULL,
  `payment_method` varchar(50) NOT NULL,
  `description` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `revenue` ADD PRIMARY KEY (`sale_id`);',
      1 => 'ALTER TABLE `revenue` MODIFY `sale_id` int(10) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  38 => 
  array (
    'name' => 'salary_advances',
    'create' => 'CREATE TABLE IF NOT EXISTS `salary_advances` (
  `id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `employee_name` varchar(255) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `advance_date` date NOT NULL,
  `deduction_month` int(11) NOT NULL,
  `deduction_year` int(11) NOT NULL,
  `notes` text DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT \'cash\',
  `status` enum(\'pending\',\'deducted\',\'cancelled\') DEFAULT \'pending\',
  `created_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `salary_advances` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_employee` (`employee_id`),
  ADD KEY `idx_status` (`status`),
  ADD KEY `idx_deduction` (`deduction_year`,`deduction_month`);',
      1 => 'ALTER TABLE `salary_advances` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  39 => 
  array (
    'name' => 'sales',
    'create' => 'CREATE TABLE IF NOT EXISTS `sales` (
  `id` int(11) NOT NULL,
  `date` date NOT NULL,
  `amount_paid` decimal(10,2) NOT NULL,
  `description` text DEFAULT NULL,
  `billing_id` int(11) NOT NULL,
  `patient_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `transaction_id` varchar(255) DEFAULT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `folder_id` varchar(255) NOT NULL,
  `payment_method` varchar(255) NOT NULL,
  `customer_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `sales` ADD PRIMARY KEY (`id`),
  ADD KEY `idx_sale_id` (`id`);',
      1 => 'ALTER TABLE `sales` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  40 => 
  array (
    'name' => 'sms_templates',
    'create' => 'CREATE TABLE IF NOT EXISTS `sms_templates` (
  `id` int(11) NOT NULL,
  `template_name` varchar(100) NOT NULL,
  `message_text` text NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `sms_templates` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `sms_templates` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  41 => 
  array (
    'name' => 'ssnit_contributions',
    'create' => 'CREATE TABLE IF NOT EXISTS `ssnit_contributions` (
  `id` int(11) NOT NULL,
  `employee_name` varchar(255) NOT NULL,
  `employee_ssnit_number` varchar(255) NOT NULL,
  `basic_salary` decimal(10,2) NOT NULL,
  `employee_contribution` decimal(10,2) NOT NULL,
  `employer_contribution` decimal(10,2) NOT NULL,
  `total_contribution` decimal(10,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
    ),
  ),
  42 => 
  array (
    'name' => 'standard_prices',
    'create' => 'CREATE TABLE IF NOT EXISTS `standard_prices` (
  `id` int(11) NOT NULL,
  `consultation_price` decimal(10,2) NOT NULL,
  `frame_price` decimal(10,2) NOT NULL,
  `lens_price` decimal(10,2) NOT NULL,
  `case_price` decimal(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `standard_prices` ADD PRIMARY KEY (`id`);',
      1 => 'ALTER TABLE `standard_prices` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  43 => 
  array (
    'name' => 'tax_records',
    'create' => 'CREATE TABLE IF NOT EXISTS `tax_records` (
  `id` int(11) NOT NULL,
  `billing_id` int(11) NOT NULL,
  `folder_id` varchar(50) NOT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `tax_formula` enum(\'TFS\',\'TFG\') NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  `nhil_amount` decimal(10,2) DEFAULT 0.00,
  `getfund_amount` decimal(10,2) DEFAULT 0.00,
  `covid_levy_amount` decimal(10,2) DEFAULT 0.00,
  `vat_amount` decimal(10,2) DEFAULT 0.00,
  `vat_flat_rate_amount` decimal(10,2) DEFAULT 0.00,
  `total_tax` decimal(10,2) NOT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `transaction_date` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `tax_records` ADD PRIMARY KEY (`id`),
  ADD KEY `billing_id` (`billing_id`),
  ADD KEY `transaction_date` (`transaction_date`);',
      1 => 'ALTER TABLE `tax_records` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  44 => 
  array (
    'name' => 'trash',
    'create' => 'CREATE TABLE IF NOT EXISTS `trash` (
  `id` int(11) NOT NULL,
  `original_table` varchar(100) NOT NULL,
  `original_id` int(11) NOT NULL,
  `original_data` longtext NOT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  `deleted_at` datetime NOT NULL,
  `restored` tinyint(1) NOT NULL DEFAULT 0,
  `restored_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `trash` ADD PRIMARY KEY (`id`),
  ADD KEY `original_table` (`original_table`),
  ADD KEY `original_id` (`original_id`),
  ADD KEY `deleted_by` (`deleted_by`);',
      1 => 'ALTER TABLE `trash` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
  45 => 
  array (
    'name' => 'users',
    'create' => 'CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL,
  `employee_status` varchar(50) NOT NULL,
  `profile_image` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `branch` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
    'post' => 
    array (
      0 => 'ALTER TABLE `users` ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);',
      1 => 'ALTER TABLE `users` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;',
    ),
  ),
),
    'foreign_keys' => array (
  0 => 'ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inv_movement_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `fk_inv_movement_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL;',
),
    'extra_tables' => array (
  0 => 
  array (
    'name' => 'internal_messages',
    'create' => 'CREATE TABLE IF NOT EXISTS `internal_messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sender_id` bigint unsigned NOT NULL,
  `recipient_id` bigint unsigned NOT NULL,
  `message` text NOT NULL,
  `read_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `internal_messages_recipient_read_idx` (`recipient_id`, `read_at`),
  KEY `internal_messages_pair_idx` (`sender_id`, `recipient_id`),
  KEY `internal_messages_created_idx` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    'post' => 
    array (
    ),
  ),
  1 => 
  array (
    'name' => 'expense_categories',
    'create' => 'CREATE TABLE IF NOT EXISTS `expense_categories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `expense_categories_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    'post' => 
    array (
    ),
  ),
  2 => 
  array (
    'name' => 'insurance_providers',
    'create' => 'CREATE TABLE IF NOT EXISTS `insurance_providers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `insurance_providers_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    'post' => 
    array (
    ),
  ),
  3 => 
  array (
    'name' => 'financial_reports',
    'create' => 'CREATE TABLE IF NOT EXISTS `financial_reports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` int unsigned NOT NULL DEFAULT 1,
  `title` varchar(255) NOT NULL,
  `report_type` varchar(50) NOT NULL,
  `month` varchar(20) NOT NULL,
  `comparison_branch_id` int unsigned DEFAULT NULL,
  `comparison_month` varchar(20) DEFAULT NULL,
  `prepared_by_name` varchar(255) NOT NULL,
  `prepared_by_id` bigint unsigned DEFAULT NULL,
  `prepared_by_role` varchar(50) NOT NULL,
  `status` enum(\'submitted\',\'validated\',\'rejected\',\'pushed_to_ceo\') NOT NULL DEFAULT \'submitted\',
  `accountant_notes` text DEFAULT NULL,
  `accountant_signature` varchar(255) DEFAULT NULL,
  `gm_notes` text DEFAULT NULL,
  `gm_signature` varchar(255) DEFAULT NULL,
  `validated_by_name` varchar(255) DEFAULT NULL,
  `validated_by_id` bigint unsigned DEFAULT NULL,
  `validated_at` timestamp NULL DEFAULT NULL,
  `pushed_to_ceo_by_name` varchar(255) DEFAULT NULL,
  `pushed_to_ceo_by_id` bigint unsigned DEFAULT NULL,
  `pushed_to_ceo_at` timestamp NULL DEFAULT NULL,
  `payload_json` longtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `financial_reports_branch_id_index` (`branch_id`),
  KEY `financial_reports_prepared_by_id_index` (`prepared_by_id`),
  KEY `financial_reports_status_index` (`status`),
  KEY `financial_reports_validated_by_id_index` (`validated_by_id`),
  KEY `financial_reports_pushed_to_ceo_by_id_index` (`pushed_to_ceo_by_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    'post' => 
    array (
    ),
  ),
  4 => 
  array (
    'name' => 'financial_report_approvals',
    'create' => 'CREATE TABLE IF NOT EXISTS `financial_report_approvals` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `report_id` bigint unsigned NOT NULL,
  `approver_id` bigint unsigned DEFAULT NULL,
  `approver_name` varchar(255) NOT NULL,
  `approver_role` varchar(50) NOT NULL,
  `action` enum(\'submitted\',\'validated\',\'rejected\',\'pushed_to_ceo\') NOT NULL,
  `notes` text DEFAULT NULL,
  `signature_path` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `financial_report_approvals_report_id_index` (`report_id`),
  KEY `financial_report_approvals_approver_id_index` (`approver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
    'post' => 
    array (
    ),
  ),
),
];
